### ISSUE TITLE
Switched sign in ocean Etc/GMT timezones?

### ISSUE THREAD

**Issue by jannikmi** [evansiroky/timezone-boundary-builder#100]
As posted in issue https://github.com/jannikmi/timezonefinder/issues/121 the sign of all ocean timezones seems to be switched. See for example:
https://timezonefinder.michelfe.it/gui/0_117.68520010023614_10.891010631283473
vs.
https://timezonefinder.michelfe.it/gui/0_-117.68520010023614_10.891010631283473

Is there some naming convention that is causing zones to the east having a negative GMT offset? That seems to be quite counterintuitive. Thx for any clarification.

**Comment by kohenkatz** [comment]
See #45 and #38
