### ISSUE TITLE
Bullhead City, AZ incorrectly identified as PST

### ISSUE THREAD

**Issue by lanegoolsby** [evansiroky/timezone-boundary-builder#103]
The lat and long for Bullhead City, AZ is being identified as Pacific Time Zone. It should be MST. I do see an alternative result that is MST, but that should be the primary result, not the secondary, correct?

[OpenMap](https://www.openstreetmap.org/relation/6695742) shows the correct state info and the [Wikidata link on that page](https://www.wikidata.org/wiki/Q79432) shows the correct timezone info. 

Example coordinates. 
35.0959f, -114.598f
35.115556f, -114.588611f

![image](https://user-images.githubusercontent.com/10758510/122102021-d32d1600-cdc9-11eb-9b96-7e3827237a9b.png)

**Comment by mattjohnsonpint** [comment]
Hi.  This is more likely related to GeoTimeZone's indexing precision,  not the source data.

Please see related issues at https://github.com/mattjohnsonpint/GeoTimeZone/issues

(I am thinking about a better solution, but it is a known issue.)

**Comment by lanegoolsby** [comment]
Should I close this issue?

**Comment by mattjohnsonpint** [comment]
Yes, since it's not an issue with the TBB data.
