### ISSUE TITLE
Australia/Currie + redefinition for nearby TimeZones

### ISSUE THREAD

**Issue by szjozsef** [evansiroky/timezone-boundary-builder#106]
with the 2020e time-zone update Australia/Currie is deprecated in favor of: Australia/Hobart.
Also there are distinct polygons for:
- Christmas Island
- Cocos (Keeling) Islands
- Norfolk Island

They can be used to construct the timezone polygons for this regions instead of cutting them out from the Australia polygon
The polygon of: Tasmania can be used to construct the timezone polygon for: Antarctica/Macquarie
The polygon of: New South Wales can be used to construct the timezone polygon for: Australia/Lord_Howe
The source definitions for : osmBoundarySources.json can be:
```
  "Christmas Island": {
    "ISO3166-1": "CX"
  },
  "Cocos (Keeling) Islands": {
    "ISO3166-1": "CC"
  },
  "Norfolk Island": {
    "ISO3166-1": "NF"
  },
```
Changes for : timezones.json
```
  "Antarctica/Macquarie": [
    {
      "op": "init",
      "source": "overpass",
      "id": "Tasmania"
    }, {
      "op": "intersect",
      "source": "manual-polygon",
      "data": [[[159,-53],[156,-56],[162,-56],[159,-53]]],
      "description": "Intersect part of Australia to isolate Macquarie Island."
    }
  ],
  "Australia/Hobart": [
    {
      "op": "init",
      "source": "overpass",
      "id": "Tasmania"
    }, {
      "op": "difference",
      "source": "manual-polygon",
      "data": [[[159,-53],[156,-56],[162,-56],[159,-53]]],
      "description": "Exclude Macquarie Island."
    }
  ],
  "Australia/Lord_Howe": [
    {
      "op": "init",
      "source": "overpass",
      "id": "New South Wales"
    }, {
      "op": "intersect",
      "source": "manual-polygon",
      "data": [[[160,-33],[160,-31],[157,-31],[160,-33]]],
      "description": "Intersect to include only Lord Howe Island."
    }
  ],
  "Indian/Christmas": [
    {
      "op": "init",
      "source": "overpass",
      "id": "Christmas Island"
    }
  ],
  "Indian/Cocos": [
    {
      "op": "init",
      "source": "overpass",
      "id": "Cocos (Keeling) Islands"
    }
  ],
  "Pacific/Norfolk": [
    {
      "op": "init",
      "source": "overpass",
      "id": "Norfolk Island"
    }
  ],
```
Whit this changes the Autralia boundary polygon is no longer required, this can be removed from osmBoundarySources.json:
```
  "Australia": {
    "ISO3166-1": "AU"
  },
```

**Comment by evansiroky** [comment]
Thanks for pointing out that `Australia/Currie` was moved to the backward file. I'll review these proposed changes and make the necessary commits.

**Comment by evansiroky** [comment]
I ended up doing this, but kept the Australia OSM relation to make sure all Australian zones use the country's territorial waters instead of just state/territory territorial waters.
