### ISSUE TITLE
OSM polygon issues

### ISSUE THREAD

**Issue by szjozsef** [evansiroky/timezone-boundary-builder#108]
I tried to run the script and while downloading the fresh polygons from overpass as defined in osmBoundarySources.json for a few regions I received validation errors, like Invalid geojson received in Overpass Result or error writing combined border to geojson:
- Bas-Uele
- Kyrgyzstan
- Tajikistan
- Tshopo
- Zacatecas

P.S. I know that this issues are not directly related to this project. but maybe somebody see the errors here and fixes the data in OSM

**Comment by szjozsef** [comment]
it seems that in mean time this relations was fixed in OSM (however there are others at this moment)

**Comment by evansiroky** [comment]
@szjozsef, every single time I have updated the data I have encountered errors like these in various parts of the world. Check out [this screen-recording video I made of me fixing a broken timezone relation](https://www.youtube.com/watch?v=hiBqa4bTox8).
