### ISSUE TITLE
Bad negative area for Africa/Lubumbashi

### ISSUE THREAD

**Issue by jonross09** [evansiroky/timezone-boundary-builder#11]
Firstly, this is great! I've been trying to figure out how to get territorial waters into the efele data set for a while, now I don't have to!

I downloaded the 2017a release, and I have some issues with the geoJson version of the data.

It looks like Africa/Lubumbashi has one negative polygon with only 4 points (3 if you don't count the dupe at the end), it also looks like it's area is 0. Also, the points go beyond 6 significant digits. Here is the json w/ a most of the points of the positive area removed for readability : 

{
    "type" : "Feature",
    "properties" : {
      "tzid" : "Africa/Lubumbashi"
    },
    "geometry" : {
      "type" : "Polygon",
      "coordinates" : [ [ [ 23.8940358, 4.8313928 ], .... a ton of points removed ....  [ 23.8940358, 4.8313928 ] ], [ [ 24.4123887, -1.7179482 ], [ 24.440029068012333, -1.735314196891881 ], [ 24.440029068012333, -1.7353141968918806 ], [ 24.4123887, -1.7179482 ] ] ]
    }
  }

**Comment by evansiroky** [comment]
I'm not sure what you mean when you say that Africa/Lubumbashi has a "negative polygon".  Can you explain what a "negative polygon" is and why it is a problem?

I do agree that having more than 6 significant digits is overkill.

**Comment by evansiroky** [comment]
ok, I see what you're talking about now.  I think this particular negative area is an artifact of some geometry operations used to build this zone.
