### ISSUE TITLE
Map only needs 4 colours.

### ISSUE THREAD

**Issue by jmesich** [evansiroky/timezone-boundary-builder#116]
Remake the map with 4 colours: https://en.wikipedia.org/wiki/Four_color_theorem

**Comment by empjustine** [comment]
As the linked page says:

> The intuitive statement of the four color theorem – "given any separation of a plane into contiguous regions, the regions can be colored using at most four colors so that no two adjacent regions have the same color" – needs to be interpreted appropriately to be correct.
> (...)
> If we required the entire territory of a country to receive the same color, then four colors are not always sufficient.

If we required the entire territory of a [non-contiguous] timezone to receive the same color, then four colors are not always sufficient.

**Comment by evansiroky** [comment]
I can see this being confusing for some timezones that touch many more than 4 other timezones. Also, the way the colors are generated is using QGIS to classify each boundary as a different color which is fairly low effort. In the end, the map in the README isn't really the important part of a release. Therefore, I'm closing this as "will not fix".
