### ISSUE TITLE
Question about gid consistency

### ISSUE THREAD

**Issue by boris-glumpler** [evansiroky/timezone-boundary-builder#126]
Hello,

just a quick question about `gid`. Can I assume that these values stay the same in between updates and could therefore be used as foreign keys? 

Cheers!

**Comment by evansiroky** [comment]
I believe this is an artifact of some GIS program that creates a unique ID for each row. There is only one provided attribute for each zone and that is the timezone identifier value (`America/Los_Angeles` for example). Therefore, I believe that `gid` value you are seeing cannot be relied upon to stay the same.
