### ISSUE TITLE
Improve OSM data in zones still containing manual definitions

### ISSUE THREAD

**Issue by evansiroky** [evansiroky/timezone-boundary-builder#140]
As a part of an effort to rely more heavily on the timezone boundary definitions as defined directly in OSM, work is being done to transition as many definitions as possible to use OSM data without any further modifications. All of the timezone boundary definitions in this project have been updated to use OSM timezone data directly wherever there appeared to be agreement between what this project was producing and the results of extracting exactly the timezone definition from OSM. However, there are still quite a few remaining boundaries that are not coded as expected in OSM. Therefore, this issue will be used to track whether timezones are coded as expected entirely within OSM.

For now, this list does not include timezones in Antarctica or those that have additional area added in Antarctica if the remaining boundary building process comes from a single OSM timezone.

Some common problems are that the boundaries in OSM are sometimes missing, include too much, include too little area, do not include territorial waters or include areas beyond territorial waters.

These zones will be checked off once the data in OSM appears to match what is currently in this project's timezone boundary definition or if additional discussion can occur that shows that the OSM data for a zone is in fact correct and the definitions in this project were wrong.

Help is wanted to edit timezone relations in OSM!

- [x] `Africa/Casablanca`
- [x] `Africa/Ceuta`
- [x] `Africa/El_Aaiun`
- [x] `Africa/Porto-Novo`
- [x] `America/Anchorage`
- [ ] `America/Chicago`
- [ ] `America/Denver`
- [x] `America/Fortaleza`
- [x] `America/Havana`
- [x] `America/Metlakatla`
- [ ] `America/New_York`
- [x] `America/Nome`
- [x] `America/Noronha`
- [x] `America/Nuuk`
- [x] `America/Puerto_Rico`
- [x] `America/Punta_Arenas`
- [x] `America/Recife`
- [x] `America/Santiago`
- [x] `America/Sao_Paulo`
- [x] `America/Sitka`
- [x] `America/St_Thomas`
- [x] `Arctic/Longyearbyen`
- [x] `Asia/Aqtau`
- [x] `Asia/Atyrau`
- [x] `Asia/Bangkok`
- [x] `Asia/Famagusta`
- [x] `Asia/Gaza`
- [x] `Asia/Hebron`
- [x] `Asia/Ho_Chi_Minh`
- [x] `Asia/Jerusalem`
- [x] `Asia/Kamchatka`
- [x] `Asia/Khandyga`
- [x] `Asia/Krasnoyarsk`
- [x] `Asia/Kuala_Lumpur`
- [x] `Asia/Magadan`
- [x] `Asia/Nicosia`
- [x] `Asia/Pyongyang`
- [x] `Asia/Qostanay`
- [x] `Asia/Qyzylorda`
- [x] `Asia/Shanghai`
- [x] `Asia/Srednekolymsk`
- [x] `Asia/Tashkent`
- [x] `Asia/Thimphu`
- [x] `Asia/Urumqi`
- [x] `Asia/Ust-Nera`
- [x] `Asia/Vladivostok`
- [x] `Asia/Yakutsk`
- [x] `Asia/Yangon`
- [x] `Asia/Yekaterinburg`
- [x] `Australia/Adelaide`
- [x] `Australia/Brisbane`
- [x] `Australia/Darwin`
- [x] `Australia/Hobart`
- [x] `Australia/Lindeman`
- [x] `Australia/Lord_Howe`
- [x] `Australia/Melbourne`
- [x] `Australia/Perth`
- [x] `Europe/Astrakhan`
- [x] `Europe/Berlin`
- [x] `Europe/Busingen`
- [x] `Europe/Kyiv`
- [x] `Europe/Kirov`
- [x] `Europe/Madrid`
- [x] `Europe/Moscow`
- [x] `Europe/Paris`
- [x] `Europe/Samara`
- [x] `Europe/Saratov`
- [x] `Europe/Volgograd`
- [x] `Indian/Kerguelen`
- [x] `Pacific/Auckland`
- [x] `Pacific/Easter`
- [x] `Pacific/Gambier`
- [x] `Pacific/Guam`
- [x] `Pacific/Honolulu`
- [x] `Pacific/Kwajalein`
- [x] `Pacific/Majuro`
- [x] `Pacific/Midway`
- [x] `Pacific/Noumea`
- [x] `Pacific/Pago_Pago`
- [x] `Pacific/Pitcairn`
- [x] `Pacific/Saipan`
- [x] `Pacific/Tahiti`

**Comment by szjozsef** [comment]
Because some ISO3166-2 code changes in [Kazakhstan](https://en.wikipedia.org/wiki/ISO_3166-2:KZ#Changes)
the following timezone sources where with error:
```
  "Atyrau Region": {
    "ISO3166-2": "KZ-ATY"
  },
  "Kostanay": {
    "ISO3166-2": "KZ-KUS"
  },
  "Kyzylorda": {
    "ISO3166-2": "KZ-KZY"
  },
  "Mangystau Region": {
    "ISO3166-2": "KZ-MAN"
  },
```
in OSM this regions had a different timezone value at the admin relation. I changed them to reflect the settings from your project, from now on (I hope nobody will revert the changes there), you can configure directly the timezone values to obtain this relations:
```
  "Asia-Atyrau-tz": {
    "timezone": "Asia/Atyrau"
  },
  "Asia-Qostanay-tz": {
    "timezone": "Asia/Qostanay"
  },
  "Asia-Qyzylorda-tz": {
    "timezone": "Asia/Qyzylorda"
  },
  "Asia-Aqtau-tz": {
    "timezone": "Asia/Aqtau"
  },
```

**Comment by evansiroky** [comment]
Looks great, @szjozsef! I have gone ahead and made the corresponding updates to this project's config files in a436cb9.

**Comment by evansiroky** [comment]
This has mostly been resolved. There are a few manual things here and there, but closing seems appropriate at this time.
