### ISSUE TITLE
issue with the time zone for the area around Antwerp (Belgium)

### ISSUE THREAD

**Issue by kovalevdmitryspb** [evansiroky/timezone-boundary-builder#143]
Hi, 
First of all, thanks for the great job you're doing.

It seems that for the area around the Belgium/Netherlands border, for instance lat=51.374781 lon=4.856555 (or 51.189673/4.932257), the timezone cannot be correctly defined.
I checked that with https://github.com/evanoberholster/timezoneLookup using releases 2022g and 2022d

**Comment by evansiroky** [comment]
After looking at both of these points, I believe the data produced by this project is correct. You may want to raise this issue with the lookup project that you referenced instead.

If you feel my assessment is in error, please add a comment noting the GPS coordinate in question, the expected timezone identifier and the actual identifier found. Also any official documentation of timezone boundaries would significantly help in determining the correct timezone at the coordinates in question.
