### ISSUE TITLE
adding "\n" to .json for parseability

### ISSUE THREAD

**Issue by MrMinimal64** [evansiroky/timezone-boundary-builder#15]
IMO it would be nice to add newline characters to the .json (after every tz or even polygon).
I am trying to parse it with python atm and with the file just having one line this is way more complicated.
With 120MB a few more characters wouldn't hurt I think. Or are there any cases where having just one line is helpful?

**Comment by evansiroky** [comment]
I think you are referring to the outputted geojson.  I think I'm going to file this under "won't fix". 
 There are plenty of 3rd party tools that can pretty print json.

**Comment by MrMinimal64** [comment]
I think you can delete this issue. I found that the easiest way to parse is the build in JSON parser of python.
