### ISSUE TITLE
2023c release

### ISSUE THREAD

**Issue by nilsnolde** [evansiroky/timezone-boundary-builder#159]
I can see that 2023c is basically 2023a: https://mm.icann.org/pipermail/tz-announce/2023-March/000079.html. So I'm not sure what 2023b release means on this repo. No change right? Seems to only be DST stuff in Lebanon.. Would you still consider releasing 2023c for consistency? (I'd like to script and auto-update both IANA and your database)

FWIW, your work is very important for https://github.com/valhalla/valhalla and lets us detect timezones for transit & traffic routing, so thanks a bunch for maintaining it!

**Comment by vsile** [comment]
2023b doesn't contain data for Europe/Riga (lat: 56.9, long: 24.1)
🙏 Please, update it.

**Comment by evansiroky** [comment]
@vsile Please open another issue for the matter about `Europe/Riga`.

@nilsnolde Please see https://github.com/evansiroky/timezone-boundary-builder/issues/158#issuecomment-1722391003
