### ISSUE TITLE
Suggestions for color palette changes used in maps

### ISSUE THREAD

**Issue by LaoshuBaby** [evansiroky/timezone-boundary-builder#160]
in the current map
https://github.com/evansiroky/timezone-boundary-builder/blob/e451aa308dc1f8b714cad13d89c2b61b396ca03a/2023b.png
There is no specific correspondence between colors and time zones. When looking at the differences in the time zone colors of some neighboring countries, if one does not know their respective time zones, one cannot see from the graph who is faster and who is slower.
(For example, Egypt and Sudan, China and Bhutan, Australia's SA and NT; without preconceived geographical knowledge, you can only see that they are "different", but not the difference from UTC)
So if there is a correlation between the color change and the difference between time zones, for example, the more red it is, the closer it is to -12, and the more blue it is, the closer it is to +12, would it be better?

<img width="401" alt="无标题" src="https://github.com/evansiroky/timezone-boundary-builder/assets/42690037/f9b3e13e-8b8c-4fa5-a767-b878233441d1">

(Also, maybe the saturation is too high? So there is another palette)

<img width="401" alt="无标题" src="https://github.com/evansiroky/timezone-boundary-builder/assets/42690037/59517bce-b711-4a0a-8fa7-e5a05d988a31">

---

This issue not means  #116

**Comment by evansiroky** [comment]
The map found within the README is only intended to be used to show an arbitrary classification of timezone boundaries to simply show they exist as an output of this project. As such, I am closing this as "will not fix". People are welcome to use the data in the releases to make their own maps to their own liking.
