### ISSUE TITLE
Brest, Belarus in wrong time zone

### ISSUE THREAD

**Issue by VasiRoum** [evansiroky/timezone-boundary-builder#161]
Hello,

I am using the lib in order to find the local timezone in the PL/BEL borders. The location Brest and its surroundings appear on the Polish end (Europe/Warsaw) +1 instead of the timezone of Europe/Minsk which has +3. I have seen the polygons for those 2 timezones in tz.json but it is too much and I can't figure out how to fix the polygons. 

Any help will be much appreciated, many thanks!

KR,
Vasilis

**Comment by evansiroky** [comment]
Are you directly using the data from this library or are you using another 3rd party library where you are seeing this result? It appears that `Europe/Minsk` should have an exact match of using the Belarus/Poland border near Brest.

<img width="728" alt="Screen Shot 2023-11-21 at 12 41 06 PM" src="https://github.com/evansiroky/timezone-boundary-builder/assets/3112493/dc974ce3-7a81-4cca-92e1-50a8485386b7">

**Comment by VasiRoum** [comment]
A 3rd party and I just saw that I am using 2017a version so probably this is the root of my trouble. I will use the latest version and try again. Thank you bringing that to my attention.

**Comment by VasiRoum** [comment]
Hello @evansiroky ,
I am using this [library](https://github.com/mapbox/timespace) as I had read from the README file. I am following the [instructions](https://github.com/mapbox/timespace) there in order to regenerate the timezones.json file but it seems that I am getting stuck when executing [quantize command](https://github.com/mapbox/timespace/blob/dab5368face8c355debff951bfbfd8d2b55b6686/regenerate/regenerate-timezones.sh#L8C1-L8C32) around the 200th zone. When I use the 2023b release, I am stuck at 200/419 and when I use the 2022g release I am stuck at 201/420. 
Could you be so kind to help me moving forward from there?

**Comment by evansiroky** [comment]
This appears to be a problem with a 3rd party library and not a problem with the data coming from this project. Please seek help from the maintainers of the 3rd party library you are trying to use.
