### ISSUE TITLE
2023b doesn't contain data for Europe/Riga (lat: 56.9, long: 24.1)

### ISSUE THREAD

**Issue by vsile** [evansiroky/timezone-boundary-builder#162]
We use [timezoneLookup](https://github.com/evanoberholster/timezoneLookup) to extract timezone.

![изображение](https://github.com/evansiroky/timezone-boundary-builder/assets/9244347/cea47344-79f9-4209-9a1f-62fcf0702ab6)

No timezone found for lat: 56.9, long: 24.1 (Europe/Riga)

**Comment by kipcole9** [comment]
Maybe thats an implementation issue in `timezonelookup`?  I use this data in a [timezone lookup implementation for Elixir](https://github.com/kimlai/tz_world) that I maintain and it returns the correct timezone so I suspect the data is correct.
```elixir
iex> TzWorld.version()
{:ok, "2023b"}

# Implementation using `{lon, lat}` order
iex> TzWorld.timezone_at {24.1, 56.9}
{:ok, "Europe/Riga"}
```

**Comment by evansiroky** [comment]
After looking at this point, I believe the data produced by this project is correct. I see that you have raised this issue with the lookup project that you referenced. I recommend continuing to pursue that option for further debugging the problem.
