### ISSUE TITLE
GHA workflow to notify on IANA changes?

### ISSUE THREAD

**Issue by nilsnolde** [evansiroky/timezone-boundary-builder#169]
We're using your fantastic efforts at https://github.com/valhalla/valhalla and recently we added a GHA workflow to auto-create a PR when https://github.com/eggert/tz had a new release. Since your repo is not coupled to that one, would you consider adding a similar workflow? I think it could help with
- less cognitive overhead for you, it could create an issue where you could comment "no need for an update" or "will get to it soon" or so
- more communicative for dependents such as us

We do wait a while before merging such an auto-PR to see if anything changes in this repo, so things are consistent, e.g. here: https://github.com/valhalla/valhalla/pull/4549. A GHA workflow would just be complimentary to your efforts and help a little bit. I'd be happy to script smth together that fits your repo better (e.g. create an issue instead of a PR), but of course no worries if you don't want to include anything like this, it does add a bit more overhead as well:)

**Comment by evansiroky** [comment]
@nilsnolde, thanks for the offer to create an automation to create a new issue whenever a timezone database release occurs! I'd gladly review a PR that does that.
