### ISSUE TITLE
Big Change to JSON File in 2023d

### ISSUE THREAD

**Issue by ChrisMarshallNY** [evansiroky/timezone-boundary-builder#172]
Hey folks, I'm the author of [this project](https://github.com/LittleGreenViper/LGV_TZ_Lookup). I don't include the timezone builder directly, but I do prescribe the use of the shapefiles found in the releases.

This concerns [the `timezones-with-oceans.geojson.zip` shapefile in the 2023d release](https://github.com/evansiroky/timezone-boundary-builder/releases/download/2023d/timezones-with-oceans.geojson.zip).

I have [a whole bunch of tests](https://github.com/LittleGreenViper/LGV_TZ_Lookup/blob/main/src/LGV_TZ_Lookup_Test.php) that I run on the built database.

Most of these tests are set right around TZ boundaries. It may have two tests, only a few kilometers apart, but on opposite sides of a boundary.

With the 2023d release, I suddenly got around half the tests, failing.

I noticed that the JSON file is 60MB smaller than the 2023b version, so I'm wondering if it may actually be the one WITHOUT oceans.

I am including the two HTML result files for the tests. The `FailedTests.html` file reflects the use of the 2023d file, and the `PassedTests.html` uses the 2023b file.

[Tests.zip](https://github.com/evansiroky/timezone-boundary-builder/files/14462452/Tests.zip)

**Comment by evansiroky** [comment]
I don't believe I am seeing what you are seeing. Are you sure you have downloaded the correct file? Also, a lot of the failed tests seem to indicate nothing was found which seems like some larger problem is going on.

**Comment by ChrisMarshallNY** [comment]
It would be very cool if it's my mistake. Here are the links to the release files that I'm downloading:

[2023d/timezones-with-oceans-now.geojson.zip](https://github.com/evansiroky/timezone-boundary-builder/releases/download/2023d/timezones-with-oceans-now.geojson.zip)

[2023b/timezones-with-oceans.geojson.zip](https://github.com/evansiroky/timezone-boundary-builder/releases/download/2023b/timezones-with-oceans.geojson.zip)

Note the significant difference in size.

![ScreenGrab](https://github.com/evansiroky/timezone-boundary-builder/assets/51290189/308e1752-f217-4272-8459-01aca5935c11)

I will get back to looking at it in an hour or so. I have to run, right now.

**Comment by zedxxx** [comment]
@ChrisMarshallNY Try this: [2023d/timezones-with-oceans.geojson.zip](https://github.com/evansiroky/timezone-boundary-builder/releases/download/2023d/timezones-with-oceans.geojson.zip) 48.6 MB

**Comment by ChrisMarshallNY** [comment]
Thanks!

**Comment by ChrisMarshallNY** [comment]
I will close this, but I don't see that file in [the releases repo](https://github.com/evansiroky/timezone-boundary-builder/releases/tag/2023d).

![ScreenGrab](https://github.com/evansiroky/timezone-boundary-builder/assets/51290189/ec2f83ac-7d45-476e-bc9a-e478cfd2f84d)

**Comment by zedxxx** [comment]
@ChrisMarshallNY click on the **Show all 16 assets** link.

**Comment by ChrisMarshallNY** [comment]
Ah! My bad. Thanks!
