### ISSUE TITLE
validation error ?

### ISSUE THREAD

**Issue by davidbarre** [evansiroky/timezone-boundary-builder#18]
Thanks for your projet

I try to execute your script like recommanded in the doc
`node --max-old-space-size=8192 index.js`

but I got this error at validation step

```
validating zones
load zones into memory
do validation
Validation error: America/Argentina/Rio_Gallegos intersects America/Punta_Arenas area: 0.2113007296132473
Validation error: America/Argentina/Rio_Gallegos intersects America/Santiago area: 0.4102222149999935
Encountered TopologyException, retry with GeometryPrecisionReducer
Validation error: America/Punta_Arenas intersects America/Santiago area: 0.21130072961324728
``` 

I'm doing something wrong ?

**Comment by davidbarre** [comment]
In fact, I only need europe, so it's not important to me to resolve this issue with Argentina => https://github.com/evansiroky/timezone-boundary-builder/issues/19

**Comment by evansiroky** [comment]
Looks like the OSM Boundaries have changed near the [Viedma Glacier](https://en.wikipedia.org/wiki/Viedma_Glacier).  Before now the countries of Chile and Argentina both didn't share this area, now they both do which is causing the validation error.
