### ISSUE TITLE
Geodetic System

### ISSUE THREAD

**Issue by amalone-eog** [evansiroky/timezone-boundary-builder#180]
Thank you everyone for giving up your time to build great open-source mapping products. I'm an indirect user of this library via timezonefinder (https://github.com/jannikmi/timezonefinder) which has been a great tool for some of my projects.

A question - **What Geodetic System do the shape files in timezone-boundary-builder adhere to?**

**Comment by evansiroky** [comment]
The timezone-boundary-builder project produces timezone boundary data using the WGS84 (World Geodetic System 1984) coordinate reference system.

**Comment by amalone-eog** [comment]
> The timezone-boundary-builder project produces timezone boundary data using the WGS84 (World Geodetic System 1984) coordinate reference system.

Awesome thank you!
