### ISSUE TITLE
Timezone subset ?

### ISSUE THREAD

**Issue by davidbarre** [evansiroky/timezone-boundary-builder#19]
Hi, 

I only need a timezone extract subset (just Europe)
I modify timezone.json and remove all timezones I don't need

is it the good solution ?

**Comment by evansiroky** [comment]
Yes, that should work.  However, I'd recommend downloading the release data and editing it in some GIS software instead since that will be less prone to errors in the boundary building script.

**Comment by evansiroky** [comment]
I just added a feature where it is possible to build the timezone shapefile from only certain zones that are specified through the command line.  See: https://github.com/evansiroky/timezone-boundary-builder#only-certain-zones
