### ISSUE TITLE
error converting geojson to geometry

### ISSUE THREAD

**Issue by anneb** [evansiroky/timezone-boundary-builder#23]
node --max-old-space-size=8192 index.js
....[some expected output]...
getting data for Atikokan-tz
downloading from overpass
waiting 4 seconds
Success, decreasing overpass request gap
combining border
error converting geojson to geometry
error converting overpass result to geojson

/timezone-boundary-builder/index.js:202
            throw e
            ^
[object Object]

Enviroment:
Windows 10
node --version
v6.9.4
**EDIT:** File: debug_geojson_read_error.json contains a Polygon representing the border of Atikokan  timezone

**Comment by evansiroky** [comment]
The relation is probably messed up in OSM.  Someone may have deleted a way or deleted the timezone tag from a way within the relation.  May have to build this zone manually.  Thanks for the report.

**Comment by anneb** [comment]
Reproduced the problem on Ubuntu 16.04, node --version => v8.0.0

After double check, file debug_geojson_read_error.json contains only one Polygon (QGIS offers to load the file both as polygon or linestring). I checked OSM and the relation has a tag "timezone"="America/Atikokan"

**Comment by evansiroky** [comment]
It appears that this problem has fixed itself!  I downloaded the data from OSM without an issue today.
