### ISSUE TITLE
Create a troubleshooting wiki page. 

### ISSUE THREAD

**Issue by evansiroky** [evansiroky/timezone-boundary-builder#27]
Topic include:
- What to do with invalid geometry errors.
- What to do with validation issues.

**Comment by GuidoS** [comment]
yes, whar should i do with invalid geom?

**Comment by evansiroky** [comment]
If at all possible, please use the data from the latest release.  There should be very limited use cases for requiring an up-to-date on-demand output of the data.  If there is a particular area that is assigned a timezone identifier that seems incorrect, please create an issue about that.  If you run into individual build errors, please create a new issue describing the problem you're running into.
