### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Solodkiy** [evansiroky/timezone-boundary-builder#28]
@evansiroky do you have any plan to releases? I need some fixes from master and I am interesting should wait release from you or build release by myself.

**Comment by evansiroky** [comment]
There will be a new release of the timezone db soon according to [chatter on the mailing list](http://mm.icann.org/pipermail/tz/2017-October/025335.html).  Therefore, there will be a new release of this library shortly thereafter.

**Comment by evansiroky** [comment]
The timezone db officially has released a new version.  I want to complete #21 and #22 before making a release from this project.  I hope to complete that by Saturday night.
