### ISSUE TITLE
Groupsing Island Chains

### ISSUE THREAD

**Issue by mj1856** [evansiroky/timezone-boundary-builder#3]
First of all, let me say THANK YOU very much for creating this!  This seems like a much more viable and accurate option than efele.net maps.  In particular, I love that you've included territorial waters, as this eliminates all the complex shoreline data in Alaska and Canada (for example).

However, I'm curious if something more can be done in defining territorial waters better for island chains?  For example, the waters in the Hawaiian Islands are all probably in the `Pacific/Honolulu` time zone, but since the territorial waters are drawn around the individual islands, only the areas where the boundaries overlap are merged.  There's a small gap between Maui and Hawaii and a larger gap between Oahu and Kauai that should also be considered part of these waters, IMHO.

![image](https://cloud.githubusercontent.com/assets/1396388/19048746/8086b62e-895c-11e6-95e9-90e451719ef9.png)

Same goes for Micronesia, Marshall Islands, and many other places.

Any thoughts on how to reconcile this without manually drawing polygons?  I really like the approach of using OpenStreetMaps as a primary source.

**Comment by evansiroky** [comment]
The boundaries of all countries are extracted directly from OSM.  Some countries have differing claims as to how far out in the sea their territory extends.  For example, Peru claims 200 nautical miles.  In the case of Hawaii here, the USA claims 12 nautical miles into the sea as their territory.  Therefore the boundaries seem quite accurate even when compared to an official source:  http://www.nauticalcharts.noaa.gov/csdl/mbound.htm

I think there may be differing opinions on how far out into the sea to extend timezones.  There are other options such as "contiguous zones" or "exclusive economic zones".  In the [Wikipedia article about timezones at sea](https://en.wikipedia.org/wiki/Time_zone#Nautical_time_zones) it states:

> A ship within the territorial waters of any nation would use that nation's standard time, but would revert to nautical standard time upon leaving its territorial waters.

I think it may be best to simply use territorial waters.

**Comment by mj1856** [comment]
Ok.  It's still much better than the other sources, so I'm good with this.  Just thought I'd ask!

**Comment by evansiroky** [comment]
Thanks for the input and I'm happy to have your blessing on this issue!
