### ISSUE TITLE
Add list of timezone lookup libraries to the README

### ISSUE THREAD

**Issue by evansiroky** [evansiroky/timezone-boundary-builder#30]

**Comment by mj1856** [comment]
FYI - I've updated [the StackOverflow page on this](https://stackoverflow.com/a/16086964/634824) as well. 
 There are three (yours, mine, and one other) that I've confirmed are using this project's data.  If you know of any others, please let me know. 😄

**Comment by mj1856** [comment]
FYI - I've updated [the StackOverflow page on this](https://stackoverflow.com/a/16086964/634824) as well. 
 There are three (yours, mine, and one other) that I've confirmed are using this project's data.  If you know of any others, please let me know. 😄

**Comment by evansiroky** [comment]
Nice!  I do know that https://github.com/darkskyapp/tz-lookup/ also uses this project's data.

**Comment by mj1856** [comment]
Cool.  Added it.

**Comment by simonw** [comment]
I just built https://timezones-api.now.sh/timezones/by_point using this data. I have an extensive write-up describing how I built it here: https://simonwillison.net/2017/Dec/12/building-a-location-time-zone-api/

**Comment by simonw** [comment]
Here's an example of a page that renders one of the shapes using Leaflet and GeoJSON: https://timezones-api.now.sh/timezones-4fbc08f/timezones/342

**Comment by BertoldVdb** [comment]
I needed to lookup the timezone based on GPS coordinates in an embedded system. I did not find a C/C++ library so I made my own: https://github.com/BertoldVdb/ZoneDetect
