### ISSUE TITLE
Asia/Krasnoyarsk and America/Santiago: Fail to select the areas

### ISSUE THREAD

**Issue by simurq** [evansiroky/timezone-boundary-builder#32]
Hi there,

When opening the shapefile in Google Earth v7.3.3832 and selecting any timezone area, GE normally navigates to that area showing tzid under the left-side 'Places' window. But this is only partially true for **Asia/Krasnoyarsk** - in fact, only a group of island polygons are visible/selectable while the rest of the Krasnoyarsk Krai remains in focus but without any noticeable polygon boundaries. No navigation is possible. I wonder if the issue is somehow related to unclosed polygon? 

**EDIT:** I have the same issue with continental Chile (America/Santiago) except a group of Pacific islands lying westwards the country.

See the image: https://i.imgur.com/EJaYdLE.jpg

Thanks!

**Comment by evansiroky** [comment]
Hmmm, the boundary for Asia/Krasnoyarsk seems to fail a geojson lint rule for polygons following the right-hand rule.  The shapefile is able to load fine for me in QGIS though.  Maybe using something like https://github.com/mapbox/geojson-rewind would fix this.

**Comment by simurq** [comment]
Strange... [Section 3.1.6](https://tools.ietf.org/html/rfc7946#section-3.1.6) of GeoJSON specification reads: 

> For Polygons with more than one of these [linear] rings, the first MUST be the exterior ring, and any others MUST be interior rings.  The exterior ring bounds the surface, and the interior rings (if present) bound holes within the surface.

AFAIU the wording of this section, although Asia/Krasnoyarsk (and probably other multigeometry objects inside the shapefile) **does not** have any inner boundaries (holes), it's probably the MultiGeometry type of the area that requires alternation of polygon rings to successfully pass the linting test.

**Comment by evansiroky** [comment]
A new release has been published.  Does the latest release still have this issue?

**Comment by evansiroky** [comment]
I'm assuming this issue has been resolved due to lack of activity.  Please reopen if this is still an issue.
