### ISSUE TITLE
Update to 2018c.

### ISSUE THREAD

**Issue by tramseyer** [evansiroky/timezone-boundary-builder#33]
Hi, would it be possible to update to 2018c any time soon?

**Comment by evansiroky** [comment]
There weren't any new zones in the timezone database in all releases up to and including 2018c.  Also, there haven't been any requests for changes to the boundaries of the zones within this project.  Therefore, the only thing that would be changed is the boundaries of the OpenStreetMap (OSM) polygons which are often quite small.  Were there any particular OSM edits that you are aware of that you think warrant creating a new release from this project?  Or perhaps an expectation of the length of time this project should wait no longer than before updating to the latest OSM data?

**Comment by tramseyer** [comment]
I am using your project within the scope of my custom Linux distribution:
- I have an IoT device with tzdata 2018c
- A device queries a tz-lookup-server (https://github.com/tramseyer/tz-lookup-server)
- The tz-lookup-server uses tz-lookup (https://github.com/darkskyapp/tz-lookup)
- tz-lookup is based on your timezone-boundary-builder

In my opinion it could make sense to use of the same tzdata version everywhere.
However, I have not looked into the tzdata and OSM changelogs.
So, if there is no benefit of updating your project to 2018c, fell free to close this issue and I will continue using 2017c.

**Comment by evansiroky** [comment]
The 2017c release from this project should be completely compatible with 2018c release from the timezone database since there aren't any new zones.  I'm going to go ahead an close unless there is a compelling case to update to the latest OpenStreetMap data.
