### ISSUE TITLE
Oceans not covered

### ISSUE THREAD

**Issue by flohoff** [evansiroky/timezone-boundary-builder#34]
Hi,
is there a way to merge with timezones on water? Die Oceans are covered with timezone stripes aswell and i'd need them.

Flo

**Comment by evansiroky** [comment]
Oceans are currently not included, but I've had enough requests for them that I think I'll try to add them to the next release.

**Comment by zedxxx** [comment]
> to the next release

@evansiroky  Will it be soon?

**Comment by evansiroky** [comment]
I can't make any promises on how soon I'll get around to it.  Also, there hasn't been a new release from the timezone database, so a new release from this project isn't something urgent or imminent right now.

In the meantime, I'm open to receiving pull requests to implement this feature if anybody is motivated.

**Comment by evansiroky** [comment]
Implemented in https://github.com/evansiroky/timezone-boundary-builder/commit/263258400940da754e363cbeca70bda1394462f7

**Comment by zedxxx** [comment]
I'm confused. I thought that ocean time zones should be like this: https://commons.wikimedia.org/wiki/File:Standard_World_Time_Zones.png

i.e., they should be a little more complicated than just +1 hour for every 15 degrees. Am I wrong?

**Comment by evansiroky** [comment]
Two sources ([(1)](https://en.wikipedia.org/wiki/Nautical_time) and [(2)](http://www.world-timezone.com/nautical-time-zones/)) both state only the rule about every 15 degrees of longitude.  The other maps that have more nuance are mainly for illustrative purposes.  I've wrote a little bit about this in the [README](https://github.com/evansiroky/timezone-boundary-builder#limitations-of-this-project).
