### ISSUE TITLE
ogr2ogr: Couldn't fetch requested layer 'OGRGeoJSON'!

### ISSUE THREAD

**Issue by kbariotis** [evansiroky/timezone-boundary-builder#35]
Trying to run in on latest MacOS.

![image](https://user-images.githubusercontent.com/605742/38108279-f55e7f72-339c-11e8-8e16-f19182fb490f.png)

**Comment by Milannv** [comment]
I have the exact same issue using when running the command that includes _all_ zones. My OS X version is 10.13.3 (latest). Thus far I have had no luck resolving the issue.

**Comment by evansiroky** [comment]
Thanks, @Milannv!  I'm going to mark this as closed.
