### ISSUE TITLE
GMT offsets in seas/oceans reversed

### ISSUE THREAD

**Issue by simurq** [evansiroky/timezone-boundary-builder#38]
Just as an example (see image below), Asia/Baku (pink) is in GMT+4 while the timezone covering the adjacent Caspian Sea (green) shows Etc/GMT-3. I think the signs for water areas must be reversed to positive (+) in easterly direction and negative (-) the way around in order to comply with other (land) time zones.

https://i.imgur.com/ZG6q0um.jpg

**Comment by evansiroky** [comment]
This is expected behavior.  You can read more about this why this is in [this entry in the timezone database](https://github.com/eggert/tz/blob/master/etcetera#L36-L51).
