### ISSUE TITLE
Zone IDs switched in Greenland

### ISSUE THREAD

**Issue by mapz-sdu** [evansiroky/timezone-boundary-builder#40]
Hey,
thanks for your great work! 
I found a small issue in the shp release with oceans: The tzid's of two polygons in Greenland are switched: America/Danmarkshavn and America/Scoresbysund. America/Danmarkshavn should be the more northern one.

Greetings

**Comment by evansiroky** [comment]
Thanks for the report!  This will be fixed in the next release.
