### ISSUE TITLE
Asia/Shanghai and Asia/Urumqi

### ISSUE THREAD

**Issue by pganssle** [evansiroky/timezone-boundary-builder#41]
From my reading of [Xinjiang Time](https://en.wikipedia.org/wiki/Xinjiang_Time), it seems to me that `Asia/Shanghai` and `Asia/Urumqi` should overlap, since both time zones are in use in Xinjiang.

I'm guessing this is a deliberate choice, but maybe there should be some alias zone created for `Asia/Shanghai` that includes the entire zone?

**Comment by evansiroky** [comment]
Yes, technically these zones do overlap.  For this specific case I've been recommending a post-process fix that is relatively low effort: if a geographic lookup says that the timezone at a certain coordinate is in `Asia/Urumqi` then the software program could simply change that to say `Asia/Shanghai` if your worldview is that all of China is on `Asia/Shanghai` time.

Nonetheless, I would assume that there some other areas where the boundaries between timezones is a little fuzzy and/or interpreted differently at the same GPS coordinate depending on who you ask. 
 So far, this project has been creating a shapefile that does not have overlapping areas.  This policy helps make QA/QC easier when checking the data quality of the boundaries of zones.  Again, `Asia/Urumqi` is probably the most prominent example of overlapping areas of differing timekeeping, but given that the post-process fix is relatively low effort for this one case I'm inclined to keep things as is unless there are more compelling cases throughout the world with sufficient documentation to justify a change.

**Comment by pganssle** [comment]
Yeah, this is fair, though I don't *love* that the default is "there is one time zone per place". These kinds of assumptions tend to get baked into stuff and then bite you when you need changes on short notice 5 years later.

In any case, I think this should probably be pretty clearly documented somewhere. My use case is not the "get time zone from location" use case that many of the consumers have. I was actually [drawing a map of these](https://github.com/pganssle/tdp-2018-dateutil-talk/blob/master/make_china_map.ipynb) and had to just manually select China as my `Asia/Shanghai`.

**Comment by pganssle** [comment]
Just as a note, one problem with this approach is that it makes doing the wrong thing easy and doing the right thing hard.

In my opinion the "right thing" when looking up time zone by location would be to find all the zones in use on a given spot and allow the user to select from among them (possibly weighted by popularity in some way). By enforcing "non-overlapping", it makes it easy for people to just create a location <-> time zone mapping, and then you have to do a workaround where you maintain *your own list* of places where overlaps can be a problem.

I would think an extra file that includes the fuzzy boundaries and overlaps would best accommodate everyone.

**Comment by evansiroky** [comment]
These are all good arguments for including overlaps.  I think I'm going to go ahead and re-open this so I can at the very least note this in the documentation but also probably include overlaps in future releases.
