### ISSUE TITLE
Can not connect the open street server?

### ISSUE THREAD

**Issue by iknow34languages** [evansiroky/timezone-boundary-builder#43]
I Try to download the Time zone datasheet,but it shows the log;

waiting 4 seconds
{ message: 'Request failed: HTTP 400', statusCode: 400 }
Increasing overpass request gap
waiting 8 seconds
{ message: 'Request failed: HTTP 400', statusCode: 400 }
Increasing overpass request gap
waiting 16 seconds
{ message: 'Request failed: HTTP 400', statusCode: 400 }
Increasing overpass request gap
waiting 32 seconds
{ message: 'Request failed: HTTP 400', statusCode: 400 }
Increasing overpass request gap
waiting 64 seconds
{ message: 'Request failed: HTTP 400', statusCode: 400 }
Increasing overpass request gap
waiting 128 seconds
{ message: 'Request failed: HTTP 400', statusCode: 400 }
Increasing overpass request gap
waiting 256 seconds

**Comment by evansiroky** [comment]
Looks like the Overpass API was rejecting the calls for not having a semicolon in part of the query.  Fix incoming.  If this doesn't work, let me know which overpass source is failing to download.

**Comment by iknow34languages** [comment]
@evansiroky 
node --max-old-space-size=8192 index.js  still failed to download
