### ISSUE TITLE
Ocean time zones are incorrect

### ISSUE THREAD

**Issue by RomanIakovlev** [evansiroky/timezone-boundary-builder#45]
The ocean time zones, i.e. the ones named like `ETC/Gmt+X` or `ETC/Gmt-X`, seem to be inverted. That is, to the east of Greenwich the `ETC/Gmt-X` is used, whereas it must be `ETC/Gmt+X`. For more detailed and visual illustration of what I mean, see this issue: https://github.com/RomanIakovlev/timeshape/issues/4#issuecomment-406504759. This is consistent in both shape files and geojson releases.

**Comment by kohenkatz** [comment]
Actually, this is how they are supposed to be. See #38 for details.

**Comment by RomanIakovlev** [comment]
Oops, I didn't know that. Thanks @kohenkatz, I've learned something new today! Closing the issue then.
