### ISSUE TITLE
Golang wrapper for timezone lookup

### ISSUE THREAD

**Issue by evanoberholster** [evansiroky/timezone-boundary-builder#51]
Thanks for compiling this data, it has been really useful.

I am using it on a project written in Golang, the source of the timezone lookup API is at: https://github.com/evanoberholster/timezoneLookup

Feel free to add it to the list of libraries if it will be useful.

Cheers!

**Comment by ugjka** [comment]
I've done something similar for my needs https://github.com/ugjka/go-tz
