### ISSUE TITLE
Asia/Shanghai Asia/Taipei overlap

### ISSUE THREAD

**Issue by c933103** [evansiroky/timezone-boundary-builder#52]
Those overlap are not necessary. These islands are disputed, but they are just being disputed in the same way as the entire territory of Taiwan is being disputed.

**Comment by evansiroky** [comment]
Ok, so what you're proposing is to have all parts of Taiwan (`Asia/Taipei`) take precedence over any areas where they overlap with China (`Asia/Shanghai`)?  If you can provide a link to a reliable source of information this could greatly improve the credibility of this decision.

**Comment by c933103** [comment]
I would need to know what is the coordinate defined for Taiwan and China in OSM database to say for sure is it the case but I am not sure how to retrieve that using the overpass turbo interface.
As for link, See https://en.wikipedia.org/wiki/Free_area_of_the_Republic_of_China , especially note the first line that the term refer to area it actually control. See also history section in wikipedia link of those islands/county you linked.

**Comment by c933103** [comment]
From the look of it, having all parts of Taiwan (Asia/Taipei) take precedence over any areas where they overlap with China (Asia/Shanghai) appears to be the correct move. There are some problems with the exact area chosen by OSM data but I guess they should be fixed in OSM instead, as in:
1. https://en.wikipedia.org/wiki/Taiping_Island is currently controlled by Taiwan instead of mainland China
2. For territorial water limit of Taiwanese islands on the west side of strait, it would be better to follow https://www.cpami.gov.tw/kids/filesys/file/chinese/new5/0930001493.pdf (Chinese link) where it listed "forbidden" zone (red line: same as territorial water for Taiwan main island) and "restricted" zone (purple line: same as contiguous zone) for Taiwan main island) that they exert control on.

**Comment by evansiroky** [comment]
This is some really good research here!  It definitely would be great to have that red line of the forbidden zone be a part of OSM.  I'll go ahead and add an operation to the boundary building process that diffs areas considered Taiwan from China.  If/when someone adds those water boundaries to OSM, they should get pulled in as part of a future update.
