### ISSUE TITLE
Asia/Hebron - Asia/Jerusalem

### ISSUE THREAD

**Issue by c933103** [evansiroky/timezone-boundary-builder#53]
See https://www.haaretz.com/israel-news/.premium-israel-moves-clock-but-palestinians-dont-1.5453010 it seems like their usage overlap in more places than just Jerusalem. I think there were also some mail in tz database mailing list that talked about it.

**Comment by evansiroky** [comment]
Thanks for creating an issue for this.  From reading the article it does appear there are places in Israeli settlements in the West Bank where two different timekeeping methods are used.  It actually looks like there are relations in OSM that describe the areas resulting from the [Oslo II Accords](https://en.wikipedia.org/wiki/West_Bank_Areas_in_the_Oslo_II_Accord).  Here is [Area C](https://www.openstreetmap.org/relation/3791785) for example.  Perhaps the thing to do here is add Areas B and C to `Asia/Jerusalem`?
