### ISSUE TITLE
Node version in readme

### ISSUE THREAD

**Issue by mj1856** [evansiroky/timezone-boundary-builder#56]
The readme states:

> The script has only been verified to run with Node.js 6 on the MacOS platform

Is this still true?  Node has evolved considerably.  I don't expect folks running the script would want to downgrade.  Node 6 (Boron) is still in "Maintenance LTS" status, but [not for much longer](https://github.com/nodejs/Release).

Thanks.

**Comment by evansiroky** [comment]
Fixed in https://github.com/evansiroky/timezone-boundary-builder/commit/45bbec0aa7ee5f60354b9803c4ff79d4d63689a9
