### ISSUE TITLE
Question for timezone data format

### ISSUE THREAD

**Issue by donglaizhang** [evansiroky/timezone-boundary-builder#57]
Hey ,

Thank you for the amazing project, and we will have a maintained timezone service. 
Just have a small question: 

Is that possible to have timezone Abbreviation Name and code, like EST, Eastern Standard Time.

Thanks

**Comment by evansiroky** [comment]
It's possible to get an abbreviation from the tzid by using some 3rd party tool or list, but this seems out of scope for this project.
