### ISSUE TITLE
Create new zone Asia/Qostanay

### ISSUE THREAD

**Issue by evansiroky** [evansiroky/timezone-boundary-builder#59]
See [this thread](https://mm.icann.org/pipermail/tz/2018-December/027319.html) on the timezone email list.

**Comment by mj1856** [comment]
Any update?  Thanks.

**Comment by evansiroky** [comment]
I'll have [2018i](https://github.com/evansiroky/timezone-boundary-builder/milestone/1) ready by the end of the weekend.
