### ISSUE TITLE
Europe/Berlin in Antarctica?

### ISSUE THREAD

**Issue by RomanIakovlev** [evansiroky/timezone-boundary-builder#61]
I'm migrating https://github.com/RomanIakovlev/timeshape to the release 2018g, and found that some of my tests are broken due to changes in bounding boxes of certain time zones, particularly of `Europe/Berlin`. I see you've added `Europe/Berlin` to Antarctic territory as part of #42. 

Unfortunately, I'm unable to understand the reason for doing so. You've posted several web links in the #42 to justify that, but in none of those pages `Europe/Berlin` is mentioned, at least explicitly. General web search also doesn't bring any more clarity. Could you please provide more details on why you have assigned `Europe/Berlin` to that segment of world in Antarctic?

**Comment by evansiroky** [comment]
The 2nd link (https://encyclopedia.timegenie.com/time_zones/antarctica/) has a section about Germany stations in Antarctica and suggests that Neumayer Station is UTC/GMT +1.  This is the same time as `Europe/Berlin`, so that is why it was coded as `Europe/Berlin`.  As you mentioned though, there isn't much certainty since `Europe/Berlin` isn't explicitly mentioned, but that entry on that website seemed to be the most credible source of information on the timezone in Antarctica in that area.  If a more credible source exists that says otherwise please re-open this issue.

**Comment by ugjka** [comment]
Certainly lacks certainty in whether they follow Europe/Berlin DST changes

**Comment by mj1856** [comment]
They are on UTC all year.  The other page is incorrect.

- https://www.timeanddate.com/time/zone/antarctica/neumayer-station-iii

- https://mm.icann.org/pipermail/tz/1997-July/009929.html

It should be simply `Etc/UTC`.

**Comment by RomanIakovlev** [comment]
@mj1856 +1 for the second link with the information directly from the station inhabitants. I've also sent them (AWI) an email with the same question a couple of days ago, after finding about this issue, but got no reply yet. I'll post here if I'll get any. But anyway, I guess it makes sense to at least re-open this issue, which I can't do myself. @evansiroky would you mind re-opening it?

**Comment by evansiroky** [comment]
Thanks for the tz mailing list archive link, @mj1856 .  I'll make this area be Etc/UTC.

**Comment by ugjka** [comment]
I got confirmation via email

> Dear Mr ********,
>
>it's UTC (like for most Antarctic stations) - as you can also see via
>the Neumayer webcam:
>https://www.awi.de/en/expedition/stations/neumayer-station-iii.html
>
>Kind Regards,
>
>Dept. of Communications and Media Relations
>
>
>
>Am 02.01.19 um 18:10 schrieb ********:
>> Gender Mr.
>> First name Ugis
>> Last name *********
>> E-Mail ugis.********@gmail.com
>> Subject Time zone observed in Neumayer Station III
>> Message Hello, I'm interested to know what time zone is observed where Neumayer Station III is located and do you also observe Daylight Saving Time.
>>
>> I'm helping to build a better timezone map on github https://github.com/evansiroky/timezone-boundary-builder
>>
>> There seems to be a lot uncertainty about this station. The current consensus is that it follows Europe/Berlin time including its DST changes.
>>
>> It would be great if you could shed some light on the issue.
>>
>> Thank you,
>> Ugis
>>

**Comment by RomanIakovlev** [comment]
Lol, I've just got exactly the same answer from them, word for word. We have probably spammed them a bit. :) But great to get another confirmation anyway.
