### ISSUE TITLE
[Q] Difference between combined-with-oceans.json and combined.json?

### ISSUE THREAD

**Issue by pdh0710** [evansiroky/timezone-boundary-builder#62]
(This is a question about this project. If there is a better place for questions, please let me know. I'll move this question to there)

I have a plan to fork a location-to-timezone lookup library using Timezone-Boundary-Builder release.
I read a issue #34  about ocean timezone, but I can not fully understand the difference between combined-with-oceans.json and combined.json.

For example, [tz-lookup](https://github.com/darkskyapp/tz-lookup) project (javascript lookup library) is using combined.json only. However, when I verified tz-lookup for some locations on Pacific Ocean, it seemed tz-lookup answered correct timezones.

Can it be possible? Or something wrong with my verification?

**Comment by evansiroky** [comment]
I think it's fine to ask questions here for now.

The `combined-with-oceans.json` file includes timezone features with timezone names `Etc/GMT-12`, `Etc/GMT-11` and so on.  The `combined.json` file does not include those timezones.  Not including these zones saves on the overall filesize.  I believe that the current version of tz-lookup (as well as my other project [node-geo-tz](https://github.com/evansiroky/node-geo-tz/)) assumes that if  no timezone is found at a coordinate, then that area must be in the open sea and therefore a simple check of the longitude can determine what timezone should be returned.  Here is the relevant code in node-geo-tz:  https://github.com/evansiroky/node-geo-tz/blob/a2be2a378ab3cbe743f0c0a6ea8a1164f85b7e9b/lib/find.js#L76-L83

**Comment by ironwallaby** [comment]
I'm the maintainer of `tz-lookup`, and yes: we currently use `combined.json` and if we don't get a hit, we assume open ocean and use the relevant `Etc/GMT` offset zone.

I'm presently planning on changing this for the next release, though it shouldn't make a difference to the output—it's merely a maintenance simplification on our end.

**Comment by pdh0710** [comment]
I compared [node-geo-tz/lib/find.js](https://github.com/evansiroky/node-geo-tz/blob/a2be2a378ab3cbe743f0c0a6ea8a1164f85b7e9b/lib/find.js#L76-L83) and [timezone-boundary-builder/index.js(2632584)](https://github.com/evansiroky/timezone-boundary-builder/commit/263258400940da754e363cbeca70bda1394462f7). It seems that there is not much difference between `combined-with-oceans.json` and `combined.json`.

`combined-with-oceans.json` **=**  `combined.json` **+** ocean zone processed by lookup program

So If a lookup program can process ocean(or open sea) timezone properly, `combined.json` is sufficient for the lookup program.

Am I right?

**Comment by evansiroky** [comment]
That's right!  timezone-boundary-builder seeks to classify all populated areas that officially follow a timekeeping method defined in the timezone database.  If there are any areas that show up as `Etc/GMT*` when they actually should be some other zone id, then there is a problem with the data outputted here.  In fact, there was such a case recently with #49.

**Comment by pdh0710** [comment]
I can clearly understand the difference between `combined-with-oceans.json` and `combined.json`. Thank you @evansiroky.

**Comment by evansiroky** [comment]
You're welcome!

**Comment by pdh0710** [comment]
Question for confirmation, again.

It seems that the contents of `expectedZoneOverlaps.json` are merged into `combined.json`. This means that two of the timezones in `combined.json` can overlap.

Is this right?

**Comment by evansiroky** [comment]
The exact boundaries in `expectedZoneOverlaps.json` only serve as a validation test against the extent of the boundaries generated during the building project.  If the generated boundary exceeds the bounding box, then a validation error is raised.  Any boundaries that overlap that are not accounted for within the bounding boxes associated with the zone overlaps are treated as a validation error causing the script to throw an error.  Therefore, the zones in that file represent a complete list of all zones that overlap.

**Comment by pdh0710** [comment]
You mean : Among timezones in `combined.json`, only timezones listed in `expectedZoneOverlaps.json` are overlapped. Thank you for your detailed explanation.
