### ISSUE TITLE
How to get a country city or area boundaries?

### ISSUE THREAD

**Issue by iknow34languages** [evansiroky/timezone-boundary-builder#70]
@evansiroky 

Nice to meet you again , Is there a simple way to get the city boundary of a country from 

OpenStreetMap data?   I want to get a whole cities boundary of a special country.

I think it's very similar way you get the whole world countries boundary;

Is there any doc for me to ref? 

Thanks

**Comment by evansiroky** [comment]
In the past, I have seen some services that provided extracts that were available for download, but I'm not sure about the availability of such a service.

It would definitely be possible to fork this library or at least parts of the code to make the custom required queries needed to download data from overpass.

Unfortunately, there aren't really any docs about it, but I'll refer you to this bit of code:

https://github.com/evansiroky/timezone-boundary-builder/blob/ccbd178a94246cd9f0bfe712a0dcfecbe14f0a3f/index.js#L147-L195
