### ISSUE TITLE
Include Navajo Nation in mapping of America/Phoenix and America/Denver.

### ISSUE THREAD

**Issue by evansiroky** [evansiroky/timezone-boundary-builder#71]
The [Navajo Nation is now defined in OpenStreetMap](https://www.openstreetmap.org/relation/9795457), so it should be used as a part of the boundary building process for `America/Phoenix` and `America/Denver`.

**Comment by mj1856** [comment]
IMHO, it would be more appropriate to assign `America/Shiprock` to this region.  It's linked to `America/Denver` presently, but was specifically created to represent the Navajo Nation.

It's also a good way to ensure any future changes that might break that link would not need a map update.

**Comment by mj1856** [comment]
Though note that `America/Shiprock` was moved to the `backward` file in 2013e.  Most implementations include this, but I suppose it depends on whether you want those zones referenced in this project or not.

**Comment by evansiroky** [comment]
Since America/Shiprock is in the backward file, I believe it doesn't make sense to include it due to a precedent that has been set of not including timezone names found in the backward file. See https://github.com/evansiroky/timezone-boundary-builder/issues/16#issuecomment-304901824.

**Comment by evansiroky** [comment]
I have verified that this data is being used with the existing data that the script extracts from OpenStreetMap.
