### ISSUE TITLE
"Asia/Shanghai" shape includes "Asia/Urumqi" shape (intersection)

### ISSUE THREAD

**Issue by JoBerkner** [evansiroky/timezone-boundary-builder#79]
I came across an issue regarding the shape of the "Asia/Shanghai" timezone. It also includes the whole of the "Asia/Urumqi" shape, thus the latter is completely inside the former. This would lead to problems regarding spatial checks inside the "Asia/Urumqi" region, e.g. when checking if a coordinate is within which timezone both the "Asia/Urumqi" and the "Asia/Shanghai" timezone would be selected. 

Here is a screenshot when the opacity of 0.5 is applied to the shapes:
![image](https://user-images.githubusercontent.com/45445027/74391080-7bce0d00-4e46-11ea-9221-a52f83381aa6.png)

**Comment by ironwallaby** [comment]
As I understand it, this is by design: the region's timezone is subject to political dispute.

**Comment by JoBerkner** [comment]
Interesting info. [Here is the Wikipedia link](https://en.wikipedia.org/wiki/Xinjiang_Time) discussing this.
