### ISSUE TITLE
How to understand international date line and kirimati time zone?

### ISSUE THREAD

**Issue by JoBerkner** [evansiroky/timezone-boundary-builder#80]
I have some hard time to really understand the concept behind the Kirimati time zone and the path of the international date line. In the shapefile you provide here the kirimati timezone only consists of the islands. However, in this photo the timezone includes the ocean around it as well. 
![Screenshot_20200215-105212_Chrome](https://user-images.githubusercontent.com/45445027/74579962-570e9c80-4fe2-11ea-9fbc-50f371b9cf50.jpg)

This is also important for the path of the international date line. 
Now my question would be: Is the ocean around the islands of the Kirimati timezone part of the nautical time zone (and thus in a different timezone like you use it in the shapefile) or part of the Kirimati timezone (and thus aligning with the international date line)?

**Comment by evansiroky** [comment]
This project includes not only the islands, but also the territorial waters claimed by the governing body of the relevant land area. However, this project does not do anything beyond the territorial water boundaries including the international date line.

So far, it seems that the primary use of drawing an international dateline is more for cartographic purposes. However, the nautical boundaries are more often used in practice than the international date line. According to [this wikipedia article](https://en.wikipedia.org/wiki/International_Date_Line#De_facto_and_de_jure_date_lines),

> Ships are supposed to adopt the standard time of a country if they are within its territorial waters within 12 nautical miles (14 mi; 22 km) of land, then revert to international time zones (15° wide pole-to-pole gores) as soon as they leave. In reality, ships use these time zones only for radio communication and similar purposes. For internal purposes, such as work and meal hours, ships use a time zone of their own choosing.

See related issue: https://github.com/evansiroky/timezone-boundary-builder/issues/3

**Comment by JoBerkner** [comment]
I see. Thanks for this!
