### ISSUE TITLE
Question : Where do timezone names in timezones.json come from?

### ISSUE THREAD

**Issue by pdh0710** [evansiroky/timezone-boundary-builder#85]
(Please excuse my English)

The releases of `timezone-boundary-builder` offers [timezone-name.json](https://github.com/evansiroky/timezone-boundary-builder/releases/download/2020a/timezone-names.json). It seems that timezone-names.json is derived from [timezones.json](https://github.com/evansiroky/timezone-boundary-builder/blob/master/timezones.json) and `timezones.json` is manually managed. Am I right?

I think there is a reference for the timezone names in `timezones.json`. What is the reference?

I tried to make a timezone name list from IANA [Timezone Database data](https://data.iana.org/time-zones/releases/tzdata2020a.tar.gz). But what I found was that there are lots of ways to make lists of timezone names.

**Comment by pdh0710** [comment]
Additionally, I tried to run `index.js` script.
```
$ node --max-old-space-size=8192 index.js
```
However, the following error was occurred while downloading `Palestinian Territories.json`, and `Palestinian Territories_combined_border_convert_to_geom_error.json` was generated.
```
.......
.......
getting data for Palestinian Territories; Downloading progress: 65.1% done - 0.0 seconds left
downloading from overpass
waiting 4 seconds
Success, decreasing overpass request gap
error writing combined border to geojson
done
error! TypeError: Cannot read property 'getGeometryType' of undefined
    at ws.write (/srv/jpl/timezone-boundary-builder/node_modules/jsts/dist/jsts.min.js:8:251603)
    at GeoJSONWriter.write (/srv/jpl/timezone-boundary-builder/node_modules/jsts/dist/jsts.min.js:8:255124)
    at geomToGeoJsonString (/srv/jpl/timezone-boundary-builder/index.js:140:39)
    at asynclib.auto.saveSingleMultiPolygon (/srv/jpl/timezone-boundary-builder/index.js:253:40)
    at runTask (/srv/jpl/timezone-boundary-builder/node_modules/async/dist/async.js:932:17)
    at /srv/jpl/timezone-boundary-builder/node_modules/async/dist/async.js:870:35
    at processQueue (/srv/jpl/timezone-boundary-builder/node_modules/async/dist/async.js:880:17)
    at taskComplete (/srv/jpl/timezone-boundary-builder/node_modules/async/dist/async.js:897:13)
    at /srv/jpl/timezone-boundary-builder/node_modules/async/dist/async.js:925:21
    at /srv/jpl/timezone-boundary-builder/node_modules/async/dist/async.js:321:20
```
I extracted `Palestinian Territories.json` from [input-data.zip](https://github.com/evansiroky/timezone-boundary-builder/releases/download/2020a/input-data.zip) and put it in `downloads` directory. Then the rest was processed without error.
It seems that Palestinian Territories boundaries had been modified erroneously, but I don't know how to handle this problem.

**Comment by evansiroky** [comment]
> (Please excuse my English)
> 
> The releases of `timezone-boundary-builder` offers [timezone-name.json](https://github.com/evansiroky/timezone-boundary-builder/releases/download/2020a/timezone-names.json). It seems that timezone-names.json is derived from [timezones.json](https://github.com/evansiroky/timezone-boundary-builder/blob/master/timezones.json) and `timezones.json` is manually managed. Am I right?

Yes, the `timezone-names.json` release file is simply a list of the manually-managed keys found in the `timezones.json` source-controlled file. 

> Additionally, I tried to run `index.js` script.
> 
> ```
> $ node --max-old-space-size=8192 index.js
> ```
> 
> However, the following error was occurred while downloading `Palestinian Territories.json`, and `Palestinian Territories_combined_border_convert_to_geom_error.json` was generated.
> 
> ```
> .......
> .......
> getting data for Palestinian Territories; Downloading progress: 65.1% done - 0.0 seconds left
> downloading from overpass
> waiting 4 seconds
> Success, decreasing overpass request gap
> error writing combined border to geojson
> done
> error! TypeError: Cannot read property 'getGeometryType' of undefined
>     at ws.write (/srv/jpl/timezone-boundary-builder/node_modules/jsts/dist/jsts.min.js:8:251603)
>     at GeoJSONWriter.write (/srv/jpl/timezone-boundary-builder/node_modules/jsts/dist/jsts.min.js:8:255124)
>     at geomToGeoJsonString (/srv/jpl/timezone-boundary-builder/index.js:140:39)
>     at asynclib.auto.saveSingleMultiPolygon (/srv/jpl/timezone-boundary-builder/index.js:253:40)
>     at runTask (/srv/jpl/timezone-boundary-builder/node_modules/async/dist/async.js:932:17)
>     at /srv/jpl/timezone-boundary-builder/node_modules/async/dist/async.js:870:35
>     at processQueue (/srv/jpl/timezone-boundary-builder/node_modules/async/dist/async.js:880:17)
>     at taskComplete (/srv/jpl/timezone-boundary-builder/node_modules/async/dist/async.js:897:13)
>     at /srv/jpl/timezone-boundary-builder/node_modules/async/dist/async.js:925:21
>     at /srv/jpl/timezone-boundary-builder/node_modules/async/dist/async.js:321:20
> ```
> 
> I extracted `Palestinian Territories.json` from [input-data.zip](https://github.com/evansiroky/timezone-boundary-builder/releases/download/2020a/input-data.zip) and put it in `downloads` directory. Then the rest was processed without error.
> It seems that someone had modified the Palestinian Territories boundaries erroneously, but I don't know how to handle this problem.

I believe you are seeing a JSTS error. I will investigate.

**Comment by evansiroky** [comment]
I did not see this error while preparing the 2020d release, so I am closing this issue.
