### ISSUE TITLE
Feature Request: Newline Delimited Format

### ISSUE THREAD

**Issue by tnightengale** [evansiroky/timezone-boundary-builder#86]
This is a request to offer the file in a viable newline delimited json format, which is a standard for many warehouses (BigQuery, Snowflake) to load data from buckets. 

As an aside, the following [jq](https://stedolan.github.io/jq/) commands can be used to convert the current offering into a newline delimited json: 
```
cat combined.json | jq '.features' | jq -c '.[]' > newlined_combined.json
```

**Comment by evansiroky** [comment]
Is this a request for a new file to be added to each release, or would it be possible to output the existing GeoJSON file in this format?

**Comment by tnightengale** [comment]
Upon further investigation, it's more an issue with BigQuery not being able to accept standard GeoJSON formats. For that reason I am closing this issue.
