### ISSUE TITLE
possible boundary builder issue?

### ISSUE THREAD

**Issue by apiszcz** [evansiroky/timezone-boundary-builder#87]
I am getting incorrect results when I use 
to combine and create ocean combined timezone
.\lib\timezonefinder\file_converter.py

Issue: https://github.com/MrMinimal64/timezonefinder/issues/107

Any thoughts on next steps to debug this?

Thanks.

**Comment by evansiroky** [comment]
I checked the 2020a data and don't believe there would be any underlying problem with the data that would result in the problem you are seeing.

**Comment by apiszcz** [comment]
Thanks, when I use timezonefinder without ocean zones it works correctly. Will give this feedback to MrMinimal64.

**Comment by evansiroky** [comment]
Closing as this does not seem to be a problem caused by this project.
