### ISSUE TITLE
Refactor Northeastern Arizona boundaries

### ISSUE THREAD

**Issue by evansiroky** [evansiroky/timezone-boundary-builder#9]
There's been a report at https://github.com/darkskyapp/tz-lookup/issues/7 that the town of Page, AZ is resolving to `America/Denver` when it should be `America/Phoenix`.

As of right now, it appears that the area around Page, AZ relies on data that was imported into OpenStreetMap from the [efele.net shapefile](http://efele.net/maps/tz/world/).  The shaded area is America/Phoenix.

<img width="535" alt="screen shot 2017-03-17 at 9 43 09 am" src="https://cloud.githubusercontent.com/assets/3112493/24054289/f0c2b654-0af8-11e7-9098-a3781cc2faed.png">

I've read a few online [articles](https://grandcanyon.com/planning/grand-canyon-time-zone/) [here](https://www.tripadvisor.com/ShowTopic-g28924-i139-k3413434-Arizona_Time_Zone_Confusion-Arizona.html) and [there](http://www.raftthecanyon.com/traveling-from-abroad/time-page-az/) that suggest that Page, AZ and surrounding areas should be in America/Phoenix.  So, I'm creating this issue to try and figure out the best way to draw the boundaries in Northeastern Arizona.  Shown below are the current boundaries:

<img width="638" alt="screen shot 2017-03-17 at 10 14 54 am" src="https://cloud.githubusercontent.com/assets/3112493/24055075/f3392a5a-0afb-11e7-99a7-4d52bf3efb73.png">

All of the shaded area is `America/Phoenix` and the unshaded is `America/Denver`.  In OSM, the boundary appears to be an import of the efele.net shapefile outlining the boundary of the Navajo Nation enclaving the Hopi Reservation.  Unfortunately, I'm not sure if an OSM relation exists for either the Navajo Nation or Hopi Reservation.

**Comment by jamesd8** [comment]
The problem appears to be an obsolete outline for the Navajo Nation. The land that Page, AZ is on used to be part of the reservation, but was transferred in a land exchange in 1957 as part of the Glen Canyon Dam project. See https://en.wikipedia.org/wiki/Page,_Arizona#History for details. 

It is now just part of AZ and as such should be on the America/Phoenix time zone. I'm not 100%, but I believe the census has up-to-date shapefiles for the Native American reservations, so perhaps that would be a way to fix this.

**Comment by evansiroky** [comment]
I'm attaching a picture below to illustrate the issue with the current OSM data:

<img width="664" alt="screen shot 2017-10-06 at 11 19 19 am" src="https://user-images.githubusercontent.com/3112493/31292494-83379264-aa88-11e7-8bc9-9409e51fe92d.png">

In this picture there are three lines to pay attention to and they are as follows:
- **Blue with white inner dashes:** this is the efele.net timezone boundary that was imported.  As you can see it is not very accurate.
- **Green with white inner dashes:** this is the outline of the Glen Canyon Nation Recreation Area
- **White dashed line:** This appears to be an import from TIGER of the city boundary for the City of Page.

Unfortunately, all of these lines don't share the same points and aren't all contiguous for the lengths needed to represent the full boundary of the Navajo Nation within Arizona.  Furthermore, the relation and boundaries of the Navajo Nation are missing entirely from OSM.  If someone could import that into OSM, that would be very helpful.  Until then, I think the best solution would be to intersect the America/Phoenix polygon with the City of Page polygon and then also difference the America/Denver polygon with the City of Page polygon and call it good.

**Comment by keith-lafortune** [comment]
Commenting to echo what jamesd8 has written above. Any solution that places Page Municipal Airport (PGA) in the correct timezone would be most welcome. The geo point we have for PGA is LAT 36.9260833 and LONG -111.4483611.

Thanks in advance for your help.

**Comment by evansiroky** [comment]
This is the current OSM Boundary for Page:

<img width="741" alt="screen shot 2017-10-06 at 11 52 44 am" src="https://user-images.githubusercontent.com/3112493/31293694-ef0b5d1e-aa8c-11e7-97a1-bdb580c305ab.png">

Looks like the airport would be fully included.
