### ISSUE TITLE
Jungholz Village is being created as ETC/GMT-1

### ISSUE THREAD

**Issue by evansiroky** [evansiroky/timezone-boundary-builder#93]
The pene-exclave of the Jungholz Village in Austria is being created as ETC/GMT-1 as of the 2020a release.

**Comment by evansiroky** [comment]
It appears that the underlying problem is due to the Austria OSM relation not being properly assembled into valid GeoJSON. Some 3rd party library is making the GeoJSON into a single Polygon feature with overlapping geometry. For now, I have manually edited the Austria GeoJSON input file which will be included in the `input-data.zip` file in the 2020d release.

I'll be leaving this issue open to try to figure out how invalid geometry was created from OSM data.

**Comment by szjozsef** [comment]
One possible solution to solve this (instead of manually fixing the polygons) until the root case will be found for the issue is to add via union the admin 8 level polygon of Jungholz Village to the polygon of Austria, this implies 2 changes:
- osmBoundarySources.json:
```
  "Jungholz, AT": {
    "name": "Jungholz",
    "admin_level": "8"
  },
```
- timezones.json:
```
  "Europe/Vienna": [
    {
      "op": "init",
      "source": "overpass",
      "id": "Austria"
    }, {
      "op": "union",
      "source": "overpass",
      "id": "Jungholz, AT",
      "description": "For some reason this polygon get eliminated, add it back as union to Austria"
    }
  ],
```

**Comment by evansiroky** [comment]
Thanks for this @szjozsef!

**Comment by evansiroky** [comment]
Calling it good for now with the change provided by @szjozsef.
