### ISSUE TITLE
small artifact polygons between timezones

### ISSUE THREAD

**Issue by jannikmi** [evansiroky/timezone-boundary-builder#95]
I noticed small artifact polygons in the ocean timezones which appear between regular timezone polygons.
One example for this are multiple polygons of the zone "Etc/GMT" between Togo and Ghana:
![artifact_polygons_GMT](https://user-images.githubusercontent.com/15111305/103411100-88e31000-4b6e-11eb-9b5b-064919116316.png)
This is the query I ran:
https://timezonefinder.michelfe.it/gui/0_-0.81298828125_4.631179340411012

Perhaps there is an easy way to fix this.
Thanks for your great work!

**Comment by evansiroky** [comment]
For this one specifically, it looks like the country boundaries of Togo and Ghana don't share the exact ways in OpenStreetMap for their boundary along a river. See https://www.openstreetmap.org/edit#map=17/10.79357/-0.04448. Someone will have to update this boundary in OpenStreetMap to fix this issue.

<img width="565" alt="Screen Shot 2021-01-29 at 11 28 04 AM" src="https://user-images.githubusercontent.com/3112493/106318695-2476a780-6225-11eb-9da5-327e10ffa535.png">

This project already has a validator that checks for areas of overlap, but it seems like the amount of overlap here wasn't large enough to get my attention during the last release QA checks that I did.

**Comment by evansiroky** [comment]
This particular issue along the country boundaries of Togo and Ghana has been fixed in OSM.
